[boris]
  version = 1

[build.dist-7-10-build]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-build"]
    ]

[build.dist-7-10-client]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-client"]
    ]

[build.dist-7-10-core]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-core"]
    ]

[build.dist-7-10-git]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-git"]
    ]

[build.dist-7-10-http]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-http"]
    ]

[build.dist-7-10-queue]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-queue"]
    ]

[build.dist-7-10-service]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-service"]
    ]

[build.dist-7-10-store]
  command = [
      ["master", "build", "dist-7-10", "-C", "boris-store"]
    ]

[build.branches-7-10-build]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-build"]
    ]

[build.branches-7-10-client]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-client"]
    ]

[build.branches-7-10-core]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-core"]
    ]

[build.branches-7-10-git]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-git"]
    ]

[build.branches-7-10-http]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-http"]
    ]

[build.branches-7-10-queue]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-queue"]
    ]

[build.branches-7-10-service]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-service"]
    ]

[build.branches-7-10-store]
  command = [
      ["master", "build", "branches-7-10", "-C", "boris-store"]
    ]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]
