[boris]
  version = 1

[build.dist-7-10-build]
  git = "refs/heads/master"

[build.dist-7-10-client]
  git = "refs/heads/master"

[build.dist-7-10-core]
  git = "refs/heads/master"

[build.dist-7-10-git]
  git = "refs/heads/master"

[build.dist-7-10-http]
  git = "refs/heads/master"

[build.dist-7-10-queue]
  git = "refs/heads/master"

[build.dist-7-10-service]
  git = "refs/heads/master"

[build.dist-7-10-store]
  git = "refs/heads/master"

[build.branches-7-10-build]
  git = "refs/heads/topic/*"

[build.branches-7-10-client]
  git = "refs/heads/topic/*"

[build.branches-7-10-core]
  git = "refs/heads/topic/*"

[build.branches-7-10-git]
  git = "refs/heads/topic/*"

[build.branches-7-10-http]
  git = "refs/heads/topic/*"

[build.branches-7-10-queue]
  git = "refs/heads/topic/*"

[build.branches-7-10-service]
  git = "refs/heads/topic/*"

[build.branches-7-10-store]
  git = "refs/heads/topic/*"
