[master]
  version = 1

[build.dist]
  PUBLISH = "true"
  BINARIES = "boris-service/dist/build/boris-service/boris-service"
  PUBLISH_LOCATION = "$AMBIATA_ARTEFACTS_MASTER"

  [build.dist.master]
    runner = "bin/ci"

[build.branches]
  PUBLISH = "true"
  BINARIES = "boris-service/dist/build/boris-service/boris-service"
  PUBLISH_LOCATION = "$AMBIATA_ARTEFACTS_BRANCHES"

  [build.branches.master]
    runner = "bin/ci"
