[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170609055811-189e18a/master-haskell-20170609055811-189e18a"
  version = 1
  sha1 = "b11f877a5f5cfda3594edbb11b911ccb2d3ee90f"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  CACHE = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "boris-http boris-http-readonly"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  CACHE = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "boris-http boris-http-readonly"
